// Hard-coded MDAC dropdown options (built-in defaults).
// To refresh: python3 update_hardcoded_options.py
// Last generated: 2026-05-06 20:52
const HARDCODED_OPTIONS = {
  "nationality": [
    "AFG - AFGHANISTAN",
    "ALB - ALBANIA",
    "DZA - ALGERIA",
    "ASM - AMERICAN SAMOA",
    "AND - ANDORRA",
    "AGO - ANGOLA",
    "AIA - ANGUILLA",
    "ATA - ANTARCTICA",
    "ATG - ANTIGUA AND BARBUDA",
    "ARG - ARGENTINA",
    "ARM - ARMENIA",
    "ABW - ARUBA",
    "AUS - AUSTRALIA",
    "AUT - AUSTRIA",
    "AZE - AZERBAIJAN",
    "BHS - BAHAMAS",
    "BHR - BAHRAIN",
    "BGD - BANGLADESH",
    "BRB - BARBADOS",
    "BLR - BELARUS",
    "BEL - BELGIUM",
    "BLZ - BELIZE",
    "BEN - BENIN",
    "BMU - BERMUDA",
    "BTN - BHUTAN",
    "BOL - BOLIVIA",
    "BIH - BOSNIA AND HERZEGOVINA",
    "BWA - BOTSWANA",
    "BVT - BOUVET ISLAND",
    "BRA - BRAZIL",
    "IOT - BRITISH INDIAN OCEAN TERRITORY",
    "GBN - BRITISH NATIONAL OVERSEAS",
    "GBO - BRITISH OVERSEAS CITIZENS",
    "GBP - BRITISH PROTECTED PERSON",
    "GBS - BRITISH SUBJECT",
    "BRN - BRUNEI DARUSSALAM",
    "BGR - BULGARIA",
    "BFA - BURKINA FASO",
    "BDI - BURUNDI",
    "KHM - CAMBODIA",
    "CMR - CAMEROON",
    "CAN - CANADA",
    "CPV - CAPE VERDE",
    "CYM - CAYMAN ISLANDS",
    "CAF - CENTRAL AFRICAN REPUBLIC",
    "TCD - CHAD",
    "CHL - CHILE",
    "CHN - CHINA",
    "CXR - CHRISTMAS ISLAND",
    "CCK - COCOS ISLANDS",
    "COL - COLOMBIA",
    "COM - COMOROS",
    "COG - CONGO",
    "COK - COOK ISLANDS",
    "CRI - COSTA RICA",
    "CIV - COTE D'IVOIRE",
    "HRV - CROATIA",
    "CUB - CUBA",
    "CYP - CYPRUS",
    "CZE - CZECH REPUBLIC",
    "PRK - DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA",
    "DPR - DEMOCRATIC PEOPLES REPUBLIC OF KOREA",
    "COD - DEMOCRATIC REPUBLIC OF THE CONGO",
    "DNK - DENMARK",
    "DJI - DJIBOUTI",
    "DMA - DOMINICA",
    "DOM - DOMINICAN REPUBLIC",
    "ECU - ECUADOR",
    "EGY - EGYPT",
    "SLV - EL SALVADOR",
    "GNQ - EQUATORIAL GUINEA",
    "ERI - ERITREA",
    "EST - ESTONIA",
    "ETH - ETHIOPIA",
    "EUE - EUROPEAN UNION LAISSER PASSER",
    "FLK - FALKLAND ISLAND (MALVINAS)",
    "FRO - FAROE ISLANDS",
    "FJI - FIJI",
    "FIN - FINLAND",
    "FXX - FINLAND, METROPOLITAN",
    "FRA - FRANCE",
    "GUF - FRENCH GUIANA",
    "PYF - FRENCH POLYNESIA",
    "ATF - FRENCH SOUTHERN TERRITORIES",
    "GAB - GABON",
    "GMB - GAMBIA",
    "GEO - GEORGIA",
    "DGR - GERMANY",
    "DEU - GERMANY",
    "GHA - GHANA",
    "GIB - GIBRALTAR",
    "GRC - GREECE",
    "GRL - GREENLAND",
    "GRD - GRENADA",
    "GLP - GUADELOUPE",
    "GUM - GUAM",
    "GTM - GUATEMALA",
    "GNB - GUIENA-BISSAU",
    "GIN - GUINEA",
    "GUY - GUYANA",
    "HTI - HAITI",
    "HMD - HEARD AND MCDONALD ISLANDS",
    "VAT - HOLY SEE (VATICAN CITY STATE)",
    "HND - HONDURAS",
    "HKG - HONG KONG",
    "HUN - HUNGARY",
    "ISL - ICELAND",
    "IND - INDIA",
    "IDN - INDONESIA",
    "IRN - IRAN",
    "IRQ - IRAQ",
    "IRL - IRELAND",
    "ISR - ISRAEL",
    "ITA - ITALY",
    "JAM - JAMAICA",
    "JPN - JAPAN",
    "JOR - JORDAN",
    "KAZ - KAZAKHSTAN",
    "KEN - KENYA",
    "KIR - KIRIBATI",
    "KWT - KUWAIT",
    "KGZ - KYRGYZSTAN",
    "LAO - LAO PDR",
    "LVA - LATVIA",
    "LBN - LEBANON",
    "LSO - LESOTHO",
    "LBR - LIBERIA",
    "LBY - LIBYA",
    "LIE - LIECHTENSTEIN",
    "LTU - LITHUANIA",
    "LUX - LUXEMBOURG",
    "MAC - MACAU",
    "MDG - MADAGASCAR",
    "MWI - MALAWI",
    "MYS - MALAYSIA",
    "MDV - MALDIVES",
    "MLI - MALI",
    "MLT - MALTA",
    "MHL - MARSHALL ISLANDS",
    "MTQ - MARTINIQUE",
    "MRT - MAURITANIA",
    "MUS - MAURITIUS",
    "MYT - MAYOTTE",
    "MEX - MEXICO",
    "FSM - MICRONESIA,FEDERATED STATES OF",
    "MCO - MONACO",
    "MNG - MONGOLIA",
    "MNE - MONTENEGRO",
    "MSR - MONTSERRAT",
    "MAR - MOROCCO",
    "MOZ - MOZAMBIQUE",
    "MMR - MYANMAR",
    "NAM - NAMIBIA",
    "NRU - NAURU",
    "NNS - NEGARA-NEGARA SUMBER",
    "NPL - NEPAL",
    "NLD - NETHERLANDS",
    "ANT - NETHERLANDS ANTILLES",
    "NTZ - NEUTRAL ZONE",
    "NCL - NEW CELEDONIA",
    "NZL - NEW ZEALAND",
    "NIC - NICARAGUA",
    "NER - NIGER",
    "NGA - NIGERIA",
    "ZZD - NIL",
    "NIU - NIUE",
    "NFK - NORFOLK ISLAND",
    "MNP - NORTHERN MARIANA ISLANDS",
    "NOR - NORWAY",
    "OMN - OMAN",
    "PAK - PAKISTAN",
    "PLW - PALAU",
    "PAL - PALESTINE",
    "PSE - PALESTINE",
    "PAN - PANAMA",
    "PNG - PAPUA NEW GUINEA",
    "PRY - PARAGUAY",
    "PER - PERU",
    "PHL - PHILIPPINES",
    "PCN - PITCAIRN ISLAND",
    "POL - POLAND",
    "PRT - PORTUGAL",
    "PRI - PUERTO RICO",
    "QAT - QATAR",
    "XXC - REFUGEE",
    "XXB - REFUGEE ARTICLE 1/1951",
    "MDA - REP OF MOLDOVA",
    "RKS - REP. KOSOVO",
    "KOR - REPUBLIC OF KOREA",
    "KOS - REPUBLIC OF KOSOVO",
    "MKD - REPUBLIC OF MACEDONIA",
    "SSD - REPUBLIC OF SOUTH SUDAN",
    "REU - REUNION",
    "ROM - ROMANIA",
    "ROU - ROMANIA",
    "RUS - RUSSIA",
    "RWA - RWANDA",
    "SHN - SAINT HELENA",
    "KNA - SAINT KITTS AND NEVIS",
    "LCA - SAINT LUCIA",
    "SPM - SAINT PIERRE AND MIQUELON",
    "VCT - SAINT VINCENT AND THE GRENADINES",
    "WSM - SAMOA",
    "SMR - SAN MARINO",
    "STP - SAO TOME AND PRINCIPE",
    "SAU - SAUDI ARABIA",
    "SEN - SENEGAL",
    "SER - SERBIA",
    "SRB - SERBIA",
    "SCG - SERBIA AND MONTENEGRO",
    "SYC - SEYCHELLES",
    "SLE - SIERRA LEONE",
    "SGP - SINGAPORE",
    "SVK - SLOVAKIA",
    "SVN - SLOVENIA",
    "SLB - SOLOMON ISLANDS",
    "SOM - SOMALIA",
    "ZAF - SOUTH AFRICA",
    "SGS - SOUTH GEORGIA & THE SOUTH SANDWICH IS",
    "ESP - SPAIN",
    "LKA - SRI LANKA",
    "ZZA - STATELESS",
    "XXA - STATELESS PERSON ARTICLE 1/1954",
    "SDN - SUDAN",
    "SUR - SURINAME",
    "SJM - SVALBARD AND JAN MAYEN ISLANDS",
    "SWZ - SWAZILAND",
    "SWE - SWEDEN",
    "CHE - SWITZERLAND",
    "SYR - SYRIA",
    "TWN - TAIWAN",
    "TJK - TAJIKISTAN",
    "TZA - TANZANIA",
    "THA - THAILAND",
    "FYR - THE FORMER YUGOSLAV REP. OF MACEDONIA",
    "ZZB - TIDAK DINYATAKAN OLEH KLN",
    "TLS - TIMOR LESTE",
    "TMP - TIMOR LESTE",
    "TGO - TOGO",
    "TKL - TOKELAU",
    "TON - TONGA",
    "TTO - TRINIDAD AND TOBAGO",
    "TUN - TUNISIA",
    "TUR - TURKIYE",
    "TKM - TURKMENISTAN",
    "TCA - TURKS AND CAICOS ISLANDS",
    "TUV - TUVALU",
    "UGA - UGANDA",
    "GBD - UK-DEPENDENT",
    "UKR - UKRAINE",
    "UNA - UN SPECIALIZED AGENCY",
    "UNH - UNHCR",
    "ARE - UNITED ARAB EMIRATES",
    "GBR - UNITED KINGDOM",
    "UNO - UNITED NATIONS ORGANIZATION",
    "UMI - UNITED STATES MINOR OUTLYING ISLANDS",
    "ZZZ - UNKNOWN",
    "ESH - UNKNOWN / UNSPECIFIED NATIONALITY",
    "XXX - UNSPECIFIED NATIONALITY",
    "URY - URUGUAY",
    "USA - USA",
    "UZB - UZBEKISTAN",
    "VUT - VANUATU",
    "VEN - VENEZUELA",
    "VNM - VIETNAM",
    "VGB - VIRGIN ISLANDS (BRITISH)",
    "VIR - VIRGIN ISLANDS (USA)",
    "WLF - WALLIS AND FUTURA ISLANDS",
    "YEM - YEMEN",
    "YUG - YUGOSLAVIA",
    "ZAR - ZAIRE",
    "ZMB - ZAMBIA",
    "ZWE - ZIMBABWE",
    "ZIM - ZIMBABWE"
  ],
  "place_of_birth": [
    "AFG - AFGHANISTAN",
    "ALB - ALBANIA",
    "DZA - ALGERIA",
    "ASM - AMERICAN SAMOA",
    "AND - ANDORRA",
    "AGO - ANGOLA",
    "AIA - ANGUILLA",
    "ATA - ANTARCTICA",
    "ATG - ANTIGUA AND BARBUDA",
    "ARG - ARGENTINA",
    "ARM - ARMENIA",
    "ABW - ARUBA",
    "AUS - AUSTRALIA",
    "AUT - AUSTRIA",
    "AZE - AZERBAIJAN",
    "BHS - BAHAMAS",
    "BHR - BAHRAIN",
    "BGD - BANGLADESH",
    "BRB - BARBADOS",
    "BLR - BELARUS",
    "BEL - BELGIUM",
    "BLZ - BELIZE",
    "BEN - BENIN",
    "BMU - BERMUDA",
    "BTN - BHUTAN",
    "BOL - BOLIVIA",
    "BIH - BOSNIA AND HERZEGOVINA",
    "BWA - BOTSWANA",
    "BVT - BOUVET ISLAND",
    "BRA - BRAZIL",
    "IOT - BRITISH INDIAN OCEAN TERRITORY",
    "GBN - BRITISH NATIONAL OVERSEAS",
    "GBO - BRITISH OVERSEAS CITIZENS",
    "GBP - BRITISH PROTECTED PERSON",
    "GBS - BRITISH SUBJECT",
    "BRN - BRUNEI DARUSSALAM",
    "BGR - BULGARIA",
    "BFA - BURKINA FASO",
    "BDI - BURUNDI",
    "KHM - CAMBODIA",
    "CMR - CAMEROON",
    "CAN - CANADA",
    "CPV - CAPE VERDE",
    "CYM - CAYMAN ISLANDS",
    "CAF - CENTRAL AFRICAN REPUBLIC",
    "TCD - CHAD",
    "CHL - CHILE",
    "CHN - CHINA",
    "CXR - CHRISTMAS ISLAND",
    "CCK - COCOS ISLANDS",
    "COL - COLOMBIA",
    "COM - COMOROS",
    "COG - CONGO",
    "COK - COOK ISLANDS",
    "CRI - COSTA RICA",
    "CIV - COTE D'IVOIRE",
    "HRV - CROATIA",
    "CUB - CUBA",
    "CYP - CYPRUS",
    "CZE - CZECH REPUBLIC",
    "PRK - DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA",
    "DPR - DEMOCRATIC PEOPLES REPUBLIC OF KOREA",
    "COD - DEMOCRATIC REPUBLIC OF THE CONGO",
    "DNK - DENMARK",
    "DJI - DJIBOUTI",
    "DMA - DOMINICA",
    "DOM - DOMINICAN REPUBLIC",
    "ECU - ECUADOR",
    "EGY - EGYPT",
    "SLV - EL SALVADOR",
    "GNQ - EQUATORIAL GUINEA",
    "ERI - ERITREA",
    "EST - ESTONIA",
    "ETH - ETHIOPIA",
    "EUE - EUROPEAN UNION LAISSER PASSER",
    "FLK - FALKLAND ISLAND (MALVINAS)",
    "FRO - FAROE ISLANDS",
    "FJI - FIJI",
    "FIN - FINLAND",
    "FXX - FINLAND, METROPOLITAN",
    "FRA - FRANCE",
    "GUF - FRENCH GUIANA",
    "PYF - FRENCH POLYNESIA",
    "ATF - FRENCH SOUTHERN TERRITORIES",
    "GAB - GABON",
    "GMB - GAMBIA",
    "GEO - GEORGIA",
    "DGR - GERMANY",
    "DEU - GERMANY",
    "GHA - GHANA",
    "GIB - GIBRALTAR",
    "GRC - GREECE",
    "GRL - GREENLAND",
    "GRD - GRENADA",
    "GLP - GUADELOUPE",
    "GUM - GUAM",
    "GTM - GUATEMALA",
    "GNB - GUIENA-BISSAU",
    "GIN - GUINEA",
    "GUY - GUYANA",
    "HTI - HAITI",
    "HMD - HEARD AND MCDONALD ISLANDS",
    "VAT - HOLY SEE (VATICAN CITY STATE)",
    "HND - HONDURAS",
    "HKG - HONG KONG",
    "HUN - HUNGARY",
    "ISL - ICELAND",
    "IND - INDIA",
    "IDN - INDONESIA",
    "IRN - IRAN",
    "IRQ - IRAQ",
    "IRL - IRELAND",
    "ISR - ISRAEL",
    "ITA - ITALY",
    "JAM - JAMAICA",
    "JPN - JAPAN",
    "JOR - JORDAN",
    "KAZ - KAZAKHSTAN",
    "KEN - KENYA",
    "KIR - KIRIBATI",
    "KWT - KUWAIT",
    "KGZ - KYRGYZSTAN",
    "LAO - LAO PDR",
    "LVA - LATVIA",
    "LBN - LEBANON",
    "LSO - LESOTHO",
    "LBR - LIBERIA",
    "LBY - LIBYA",
    "LIE - LIECHTENSTEIN",
    "LTU - LITHUANIA",
    "LUX - LUXEMBOURG",
    "MAC - MACAU",
    "MDG - MADAGASCAR",
    "MWI - MALAWI",
    "MYS - MALAYSIA",
    "MDV - MALDIVES",
    "MLI - MALI",
    "MLT - MALTA",
    "MHL - MARSHALL ISLANDS",
    "MTQ - MARTINIQUE",
    "MRT - MAURITANIA",
    "MUS - MAURITIUS",
    "MYT - MAYOTTE",
    "MEX - MEXICO",
    "FSM - MICRONESIA,FEDERATED STATES OF",
    "MCO - MONACO",
    "MNG - MONGOLIA",
    "MNE - MONTENEGRO",
    "MSR - MONTSERRAT",
    "MAR - MOROCCO",
    "MOZ - MOZAMBIQUE",
    "MMR - MYANMAR",
    "NAM - NAMIBIA",
    "NRU - NAURU",
    "NNS - NEGARA-NEGARA SUMBER",
    "NPL - NEPAL",
    "NLD - NETHERLANDS",
    "ANT - NETHERLANDS ANTILLES",
    "NTZ - NEUTRAL ZONE",
    "NCL - NEW CELEDONIA",
    "NZL - NEW ZEALAND",
    "NIC - NICARAGUA",
    "NER - NIGER",
    "NGA - NIGERIA",
    "ZZD - NIL",
    "NIU - NIUE",
    "NFK - NORFOLK ISLAND",
    "MNP - NORTHERN MARIANA ISLANDS",
    "NOR - NORWAY",
    "OMN - OMAN",
    "PAK - PAKISTAN",
    "PLW - PALAU",
    "PAL - PALESTINE",
    "PSE - PALESTINE",
    "PAN - PANAMA",
    "PNG - PAPUA NEW GUINEA",
    "PRY - PARAGUAY",
    "PER - PERU",
    "PHL - PHILIPPINES",
    "PCN - PITCAIRN ISLAND",
    "POL - POLAND",
    "PRT - PORTUGAL",
    "PRI - PUERTO RICO",
    "QAT - QATAR",
    "XXC - REFUGEE",
    "XXB - REFUGEE ARTICLE 1/1951",
    "MDA - REP OF MOLDOVA",
    "RKS - REP. KOSOVO",
    "KOR - REPUBLIC OF KOREA",
    "KOS - REPUBLIC OF KOSOVO",
    "MKD - REPUBLIC OF MACEDONIA",
    "SSD - REPUBLIC OF SOUTH SUDAN",
    "REU - REUNION",
    "ROM - ROMANIA",
    "ROU - ROMANIA",
    "RUS - RUSSIA",
    "RWA - RWANDA",
    "SHN - SAINT HELENA",
    "KNA - SAINT KITTS AND NEVIS",
    "LCA - SAINT LUCIA",
    "SPM - SAINT PIERRE AND MIQUELON",
    "VCT - SAINT VINCENT AND THE GRENADINES",
    "WSM - SAMOA",
    "SMR - SAN MARINO",
    "STP - SAO TOME AND PRINCIPE",
    "SAU - SAUDI ARABIA",
    "SEN - SENEGAL",
    "SER - SERBIA",
    "SRB - SERBIA",
    "SCG - SERBIA AND MONTENEGRO",
    "SYC - SEYCHELLES",
    "SLE - SIERRA LEONE",
    "SGP - SINGAPORE",
    "SVK - SLOVAKIA",
    "SVN - SLOVENIA",
    "SLB - SOLOMON ISLANDS",
    "SOM - SOMALIA",
    "ZAF - SOUTH AFRICA",
    "SGS - SOUTH GEORGIA & THE SOUTH SANDWICH IS",
    "ESP - SPAIN",
    "LKA - SRI LANKA",
    "ZZA - STATELESS",
    "XXA - STATELESS PERSON ARTICLE 1/1954",
    "SDN - SUDAN",
    "SUR - SURINAME",
    "SJM - SVALBARD AND JAN MAYEN ISLANDS",
    "SWZ - SWAZILAND",
    "SWE - SWEDEN",
    "CHE - SWITZERLAND",
    "SYR - SYRIA",
    "TWN - TAIWAN",
    "TJK - TAJIKISTAN",
    "TZA - TANZANIA",
    "THA - THAILAND",
    "FYR - THE FORMER YUGOSLAV REP. OF MACEDONIA",
    "ZZB - TIDAK DINYATAKAN OLEH KLN",
    "TLS - TIMOR LESTE",
    "TMP - TIMOR LESTE",
    "TGO - TOGO",
    "TKL - TOKELAU",
    "TON - TONGA",
    "TTO - TRINIDAD AND TOBAGO",
    "TUN - TUNISIA",
    "TUR - TURKIYE",
    "TKM - TURKMENISTAN",
    "TCA - TURKS AND CAICOS ISLANDS",
    "TUV - TUVALU",
    "UGA - UGANDA",
    "GBD - UK-DEPENDENT",
    "UKR - UKRAINE",
    "UNA - UN SPECIALIZED AGENCY",
    "UNH - UNHCR",
    "ARE - UNITED ARAB EMIRATES",
    "GBR - UNITED KINGDOM",
    "UNO - UNITED NATIONS ORGANIZATION",
    "UMI - UNITED STATES MINOR OUTLYING ISLANDS",
    "ZZZ - UNKNOWN",
    "ESH - UNKNOWN / UNSPECIFIED NATIONALITY",
    "XXX - UNSPECIFIED NATIONALITY",
    "URY - URUGUAY",
    "USA - USA",
    "UZB - UZBEKISTAN",
    "VUT - VANUATU",
    "VEN - VENEZUELA",
    "VNM - VIETNAM",
    "VGB - VIRGIN ISLANDS (BRITISH)",
    "VIR - VIRGIN ISLANDS (USA)",
    "WLF - WALLIS AND FUTURA ISLANDS",
    "YEM - YEMEN",
    "YUG - YUGOSLAVIA",
    "ZAR - ZAIRE",
    "ZMB - ZAMBIA",
    "ZWE - ZIMBABWE",
    "ZIM - ZIMBABWE"
  ],
  "sex": [
    "MALE",
    "FEMALE"
  ],
  "phone_country_code": [
    "( 1 ) CANADA",
    "( 1 ) UNITED STATES",
    "( 1242 ) BAHAMAS",
    "( 1246 ) BARBADOS",
    "( 1264 ) ANGUILLA",
    "( 1268 ) ANTIGUA AND BARBUDA",
    "( 1284 ) BRITISH VIRGIN ISLANDS",
    "( 1340 ) U.S. VIRGIN ISLANDS",
    "( 1345 ) CAYMAN ISLANDS",
    "( 1441 ) BERMUDA",
    "( 1473 ) GRENADA",
    "( 1649 ) TURKS AND CAICOS ISLANDS",
    "( 1664 ) MONTSERRAT",
    "( 1670 ) NORTHERN MARIANA ISLANDS",
    "( 1671 ) GUAM",
    "( 1684 ) AMERICAN SAMOA",
    "( 1721 ) SINT MAARTEN",
    "( 1758 ) SAINT LUCIA",
    "( 1767 ) DOMINICA",
    "( 1784 ) SAINT VINCENT AND THE GRENADINES",
    "( 1787 ) PUERTO RICO",
    "( 1809 ) DOMINICAN REPUBLIC",
    "( 1829 ) DOMINICAN REPUBLIC",
    "( 1849 ) DOMINICAN REPUBLIC",
    "( 1868 ) TRINIDAD AND TOBAGO",
    "( 1869 ) SAINT KITTS AND NEVIS",
    "( 1876 ) JAMAICA",
    "( 1939 ) PUERTO RICO",
    "( 20 ) EGYPT",
    "( 211 ) SOUTH SUDAN",
    "( ) UNKNOWN / UNSPECIFIED NATIONALITY",
    "( 212 ) MOROCCO",
    "( 213 ) ALGERIA",
    "( 216 ) TUNISIA",
    "( 218 ) LIBYA",
    "( 220 ) GAMBIA",
    "( 221 ) SENEGAL",
    "( 222 ) MAURITANIA",
    "( 223 ) MALI",
    "( 224 ) GUINEA",
    "( 225 ) IVORY COAST",
    "( 226 ) BURKINA FASO",
    "( 227 ) NIGER",
    "( 228 ) TOGO",
    "( 229 ) BENIN",
    "( 230 ) MAURITIUS",
    "( 231 ) LIBERIA",
    "( 232 ) SIERRA LEONE",
    "( 233 ) GHANA",
    "( 234 ) NIGERIA",
    "( 235 ) CHAD",
    "( 236 ) CENTRAL AFRICAN REPUBLIC",
    "( 237 ) CAMEROON",
    "( 238 ) CAPE VERDE",
    "( 239 ) SAO TOME AND PRINCIPE",
    "( 240 ) EQUATORIAL GUINEA",
    "( 241 ) GABON",
    "( 242 ) REPUBLIC OF THE CONGO",
    "( 243 ) DEMOCRATIC REPUBLIC OF THE CONGO",
    "( 244 ) ANGOLA",
    "( 245 ) GUINEABISSAU",
    "( 246 ) BRITISH INDIAN OCEAN TERRITORY",
    "( 248 ) SEYCHELLES",
    "( 249 ) SUDAN",
    "( 250 ) RWANDA",
    "( 251 ) ETHIOPIA",
    "( 252 ) SOMALIA",
    "( 253 ) DJIBOUTI",
    "( 254 ) KENYA",
    "( 255 ) TANZANIA",
    "( 256 ) UGANDA",
    "( 257 ) BURUNDI",
    "( 258 ) MOZAMBIQUE",
    "( 260 ) ZAMBIA",
    "( 261 ) MADAGASCAR",
    "( 262 ) MAYOTTE",
    "( 262 ) REUNION",
    "( 263 ) ZIMBABWE",
    "( 264 ) NAMIBIA",
    "( 265 ) MALAWI",
    "( 266 ) LESOTHO",
    "( 267 ) BOTSWANA",
    "( 268 ) SWAZILAND",
    "( 269 ) COMOROS",
    "( 27 ) SOUTH AFRICA",
    "( 290 ) SAINT HELENA",
    "( 291 ) ERITREA",
    "( 297 ) ARUBA",
    "( 298 ) FAROE ISLANDS",
    "( 299 ) GREENLAND",
    "( 30 ) GREECE",
    "( 31 ) NETHERLANDS",
    "( 32 ) BELGIUM",
    "( 33 ) FRANCE",
    "( 34 ) SPAIN",
    "( 350 ) GIBRALTAR",
    "( 351 ) PORTUGAL",
    "( 352 ) LUXEMBOURG",
    "( 353 ) IRELAND",
    "( 354 ) ICELAND",
    "( 355 ) ALBANIA",
    "( 356 ) MALTA",
    "( 357 ) CYPRUS",
    "( 358 ) FINLAND",
    "( 359 ) BULGARIA",
    "( 36 ) HUNGARY",
    "( 370 ) LITHUANIA",
    "( 371 ) LATVIA",
    "( 372 ) ESTONIA",
    "( 373 ) MOLDOVA",
    "( 374 ) ARMENIA",
    "( 375 ) BELARUS",
    "( 376 ) ANDORRA",
    "( 377 ) MONACO",
    "( 378 ) SAN MARINO",
    "( 379 ) VATICAN",
    "( 380 ) UKRAINE",
    "( 381 ) SERBIA",
    "( 382 ) MONTENEGRO",
    "( 383 ) KOSOVO",
    "( 385 ) CROATIA",
    "( 386 ) SLOVENIA",
    "( 387 ) BOSNIA AND HERZEGOVINA",
    "( 389 ) MACEDONIA",
    "( 39 ) ITALY",
    "( 40 ) ROMANIA",
    "( 41 ) SWITZERLAND",
    "( 420 ) CZECH REPUBLIC",
    "( 421 ) SLOVAKIA",
    "( 423 ) LIECHTENSTEIN",
    "( 43 ) AUSTRIA",
    "( 44 ) UNITED KINGDOM",
    "( 441481 ) GUERNSEY",
    "( 441534 ) JERSEY",
    "( 441624 ) ISLE OF MAN",
    "( 45 ) DENMARK",
    "( 46 ) SWEDEN",
    "( 47 ) NORWAY",
    "( 47 ) SVALBARD AND JAN MAYEN",
    "( 48 ) POLAND",
    "( 49 ) GERMANY",
    "( 500 ) FALKLAND ISLANDS",
    "( 501 ) BELIZE",
    "( 502 ) GUATEMALA",
    "( 503 ) EL SALVADOR",
    "( 504 ) HONDURAS",
    "( 505 ) NICARAGUA",
    "( 506 ) COSTA RICA",
    "( 507 ) PANAMA",
    "( 508 ) SAINT PIERRE AND MIQUELON",
    "( 509 ) HAITI",
    "( 51 ) PERU",
    "( 52 ) MEXICO",
    "( 53 ) CUBA",
    "( 54 ) ARGENTINA",
    "( 55 ) BRAZIL",
    "( 56 ) CHILE",
    "( 57 ) COLOMBIA",
    "( 58 ) VENEZUELA",
    "( 590 ) SAINT BARTHELEMY",
    "( 590 ) SAINT MARTIN",
    "( 591 ) BOLIVIA",
    "( 592 ) GUYANA",
    "( 593 ) ECUADOR",
    "( 595 ) PARAGUAY",
    "( 597 ) SURINAME",
    "( 598 ) URUGUAY",
    "( 599 ) NETHERLANDS ANTILLES",
    "( 599 ) CURACAO",
    "( 60 ) MALAYSIA",
    "( 61 ) AUSTRALIA",
    "( 61 ) COCOS ISLANDS",
    "( 61 ) CHRISTMAS ISLAND",
    "( 62 ) INDONESIA",
    "( 63 ) PHILIPPINES",
    "( 64 ) NEW ZEALAND",
    "( 64 ) PITCAIRN",
    "( 65 ) SINGAPORE",
    "( 66 ) THAILAND",
    "( 670 ) EAST TIMOR",
    "( 672 ) ANTARCTICA",
    "( 673 ) BRUNEI",
    "( 674 ) NAURU",
    "( 675 ) PAPUA NEW GUINEA",
    "( 676 ) TONGA",
    "( 677 ) SOLOMON ISLANDS",
    "( 678 ) VANUATU",
    "( 679 ) FIJI",
    "( 680 ) PALAU",
    "( 681 ) WALLIS AND FUTUNA",
    "( 682 ) COOK ISLANDS",
    "( 683 ) NIUE",
    "( 685 ) SAMOA",
    "( 686 ) KIRIBATI",
    "( 687 ) NEW CALEDONIA",
    "( 688 ) TUVALU",
    "( 689 ) FRENCH POLYNESIA",
    "( 690 ) TOKELAU",
    "( 691 ) MICRONESIA",
    "( 692 ) MARSHALL ISLANDS",
    "( 7 ) KAZAKHSTAN",
    "( 7 ) RUSSIA",
    "( 81 ) JAPAN",
    "( 82 ) SOUTH KOREA",
    "( 84 ) VIETNAM",
    "( 850 ) NORTH KOREA",
    "( 852 ) HONG KONG",
    "( 853 ) MACAU",
    "( 855 ) CAMBODIA",
    "( 856 ) LAOS",
    "( 86 ) CHINA",
    "( 880 ) BANGLADESH",
    "( 886 ) TAIWAN",
    "( 90 ) TURKIYE",
    "( 91 ) INDIA",
    "( 92 ) PAKISTAN",
    "( 93 ) AFGHANISTAN",
    "( 94 ) SRI LANKA",
    "( 95 ) MYANMAR",
    "( 960 ) MALDIVES",
    "( 961 ) LEBANON",
    "( 962 ) JORDAN",
    "( 963 ) SYRIA",
    "( 964 ) IRAQ",
    "( 965 ) KUWAIT",
    "( 966 ) SAUDI ARABIA",
    "( 967 ) YEMEN",
    "( 968 ) OMAN",
    "( 970 ) PALESTINE",
    "( 971 ) UNITED ARAB EMIRATES",
    "( 972 ) ISRAEL",
    "( 973 ) BAHRAIN",
    "( 974 ) QATAR",
    "( 975 ) BHUTAN",
    "( 976 ) MONGOLIA",
    "( 977 ) NEPAL",
    "( 98 ) IRAN",
    "( 992 ) TAJIKISTAN",
    "( 993 ) TURKMENISTAN",
    "( 994 ) AZERBAIJAN",
    "( 995 ) GEORGIA",
    "( 996 ) KYRGYZSTAN",
    "( 998 ) UZBEKISTAN"
  ],
  "mode": [
    "AIR",
    "LAND",
    "SEA"
  ],
  "last_port_of_embarkation": [
    "AFG - AFGHANISTAN",
    "ALB - ALBANIA",
    "DZA - ALGERIA",
    "ASM - AMERICAN SAMOA",
    "AND - ANDORRA",
    "AGO - ANGOLA",
    "AIA - ANGUILLA",
    "ATA - ANTARCTICA",
    "ATG - ANTIGUA AND BARBUDA",
    "ARG - ARGENTINA",
    "ARM - ARMENIA",
    "ABW - ARUBA",
    "AUS - AUSTRALIA",
    "AUT - AUSTRIA",
    "AZE - AZERBAIJAN",
    "BHS - BAHAMAS",
    "BHR - BAHRAIN",
    "BGD - BANGLADESH",
    "BRB - BARBADOS",
    "BLR - BELARUS",
    "BEL - BELGIUM",
    "BLZ - BELIZE",
    "BEN - BENIN",
    "BMU - BERMUDA",
    "BTN - BHUTAN",
    "BOL - BOLIVIA",
    "BIH - BOSNIA AND HERZEGOVINA",
    "BWA - BOTSWANA",
    "BVT - BOUVET ISLAND",
    "BRA - BRAZIL",
    "IOT - BRITISH INDIAN OCEAN TERRITORY",
    "GBN - BRITISH NATIONAL OVERSEAS",
    "GBO - BRITISH OVERSEAS CITIZENS",
    "GBP - BRITISH PROTECTED PERSON",
    "GBS - BRITISH SUBJECT",
    "BRN - BRUNEI DARUSSALAM",
    "BGR - BULGARIA",
    "BFA - BURKINA FASO",
    "BDI - BURUNDI",
    "KHM - CAMBODIA",
    "CMR - CAMEROON",
    "CAN - CANADA",
    "CPV - CAPE VERDE",
    "CYM - CAYMAN ISLANDS",
    "CAF - CENTRAL AFRICAN REPUBLIC",
    "TCD - CHAD",
    "CHL - CHILE",
    "CHN - CHINA",
    "CXR - CHRISTMAS ISLAND",
    "CCK - COCOS ISLANDS",
    "COL - COLOMBIA",
    "COM - COMOROS",
    "COG - CONGO",
    "COK - COOK ISLANDS",
    "CRI - COSTA RICA",
    "CIV - COTE D'IVOIRE",
    "HRV - CROATIA",
    "CUB - CUBA",
    "CYP - CYPRUS",
    "CZE - CZECH REPUBLIC",
    "PRK - DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA",
    "DPR - DEMOCRATIC PEOPLES REPUBLIC OF KOREA",
    "COD - DEMOCRATIC REPUBLIC OF THE CONGO",
    "DNK - DENMARK",
    "DJI - DJIBOUTI",
    "DMA - DOMINICA",
    "DOM - DOMINICAN REPUBLIC",
    "ECU - ECUADOR",
    "EGY - EGYPT",
    "SLV - EL SALVADOR",
    "GNQ - EQUATORIAL GUINEA",
    "ERI - ERITREA",
    "EST - ESTONIA",
    "ETH - ETHIOPIA",
    "EUE - EUROPEAN UNION LAISSER PASSER",
    "FLK - FALKLAND ISLAND (MALVINAS)",
    "FRO - FAROE ISLANDS",
    "FJI - FIJI",
    "FIN - FINLAND",
    "FXX - FINLAND, METROPOLITAN",
    "FRA - FRANCE",
    "GUF - FRENCH GUIANA",
    "PYF - FRENCH POLYNESIA",
    "ATF - FRENCH SOUTHERN TERRITORIES",
    "GAB - GABON",
    "GMB - GAMBIA",
    "GEO - GEORGIA",
    "DGR - GERMANY",
    "DEU - GERMANY",
    "GHA - GHANA",
    "GIB - GIBRALTAR",
    "GRC - GREECE",
    "GRL - GREENLAND",
    "GRD - GRENADA",
    "GLP - GUADELOUPE",
    "GUM - GUAM",
    "GTM - GUATEMALA",
    "GNB - GUIENA-BISSAU",
    "GIN - GUINEA",
    "GUY - GUYANA",
    "HTI - HAITI",
    "HMD - HEARD AND MCDONALD ISLANDS",
    "VAT - HOLY SEE (VATICAN CITY STATE)",
    "HND - HONDURAS",
    "HKG - HONG KONG",
    "HUN - HUNGARY",
    "ISL - ICELAND",
    "IND - INDIA",
    "IDN - INDONESIA",
    "IRN - IRAN",
    "IRQ - IRAQ",
    "IRL - IRELAND",
    "ISR - ISRAEL",
    "ITA - ITALY",
    "JAM - JAMAICA",
    "JPN - JAPAN",
    "JOR - JORDAN",
    "KAZ - KAZAKHSTAN",
    "KEN - KENYA",
    "KIR - KIRIBATI",
    "KWT - KUWAIT",
    "KGZ - KYRGYZSTAN",
    "LAO - LAO PDR",
    "LVA - LATVIA",
    "LBN - LEBANON",
    "LSO - LESOTHO",
    "LBR - LIBERIA",
    "LBY - LIBYA",
    "LIE - LIECHTENSTEIN",
    "LTU - LITHUANIA",
    "LUX - LUXEMBOURG",
    "MAC - MACAU",
    "MDG - MADAGASCAR",
    "MWI - MALAWI",
    "MYS - MALAYSIA",
    "MDV - MALDIVES",
    "MLI - MALI",
    "MLT - MALTA",
    "MHL - MARSHALL ISLANDS",
    "MTQ - MARTINIQUE",
    "MRT - MAURITANIA",
    "MUS - MAURITIUS",
    "MYT - MAYOTTE",
    "MEX - MEXICO",
    "FSM - MICRONESIA,FEDERATED STATES OF",
    "MCO - MONACO",
    "MNG - MONGOLIA",
    "MNE - MONTENEGRO",
    "MSR - MONTSERRAT",
    "MAR - MOROCCO",
    "MOZ - MOZAMBIQUE",
    "MMR - MYANMAR",
    "NAM - NAMIBIA",
    "NRU - NAURU",
    "NNS - NEGARA-NEGARA SUMBER",
    "NPL - NEPAL",
    "NLD - NETHERLANDS",
    "ANT - NETHERLANDS ANTILLES",
    "NTZ - NEUTRAL ZONE",
    "NCL - NEW CELEDONIA",
    "NZL - NEW ZEALAND",
    "NIC - NICARAGUA",
    "NER - NIGER",
    "NGA - NIGERIA",
    "ZZD - NIL",
    "NIU - NIUE",
    "NFK - NORFOLK ISLAND",
    "MNP - NORTHERN MARIANA ISLANDS",
    "NOR - NORWAY",
    "OMN - OMAN",
    "PAK - PAKISTAN",
    "PLW - PALAU",
    "PAL - PALESTINE",
    "PSE - PALESTINE",
    "PAN - PANAMA",
    "PNG - PAPUA NEW GUINEA",
    "PRY - PARAGUAY",
    "PER - PERU",
    "PHL - PHILIPPINES",
    "PCN - PITCAIRN ISLAND",
    "POL - POLAND",
    "PRT - PORTUGAL",
    "PRI - PUERTO RICO",
    "QAT - QATAR",
    "XXC - REFUGEE",
    "XXB - REFUGEE ARTICLE 1/1951",
    "MDA - REP OF MOLDOVA",
    "RKS - REP. KOSOVO",
    "KOR - REPUBLIC OF KOREA",
    "KOS - REPUBLIC OF KOSOVO",
    "MKD - REPUBLIC OF MACEDONIA",
    "ROS - REPUBLIC OF SOMALILAND",
    "SSD - REPUBLIC OF SOUTH SUDAN",
    "REU - REUNION",
    "ROM - ROMANIA",
    "ROU - ROMANIA",
    "RUS - RUSSIA",
    "RWA - RWANDA",
    "SHN - SAINT HELENA",
    "KNA - SAINT KITTS AND NEVIS",
    "LCA - SAINT LUCIA",
    "SPM - SAINT PIERRE AND MIQUELON",
    "VCT - SAINT VINCENT AND THE GRENADINES",
    "WSM - SAMOA",
    "SMR - SAN MARINO",
    "STP - SAO TOME AND PRINCIPE",
    "SAU - SAUDI ARABIA",
    "SEN - SENEGAL",
    "SER - SERBIA",
    "SRB - SERBIA",
    "SCG - SERBIA AND MONTENEGRO",
    "SYC - SEYCHELLES",
    "SLE - SIERRA LEONE",
    "SGP - SINGAPORE",
    "SVK - SLOVAKIA",
    "SVN - SLOVENIA",
    "SLB - SOLOMON ISLANDS",
    "SOM - SOMALIA",
    "ZAF - SOUTH AFRICA",
    "SGS - SOUTH GEORGIA & THE SOUTH SANDWICH IS",
    "ESP - SPAIN",
    "LKA - SRI LANKA",
    "ZZA - STATELESS",
    "XXA - STATELESS PERSON ARTICLE 1/1954",
    "SDN - SUDAN",
    "SUR - SURINAME",
    "SJM - SVALBARD AND JAN MAYEN ISLANDS",
    "SWZ - SWAZILAND",
    "SWE - SWEDEN",
    "CHE - SWITZERLAND",
    "SYR - SYRIA",
    "TWN - TAIWAN",
    "TJK - TAJIKISTAN",
    "TZA - TANZANIA",
    "THA - THAILAND",
    "FYR - THE FORMER YUGOSLAV REP. OF MACEDONIA",
    "ZZB - TIDAK DINYATAKAN OLEH KLN",
    "TLS - TIMOR LESTE",
    "TMP - TIMOR LESTE",
    "TGO - TOGO",
    "TKL - TOKELAU",
    "TON - TONGA",
    "TTO - TRINIDAD AND TOBAGO",
    "TUN - TUNISIA",
    "TUR - TURKIYE",
    "TKM - TURKMENISTAN",
    "TCA - TURKS AND CAICOS ISLANDS",
    "TUV - TUVALU",
    "UGA - UGANDA",
    "GBD - UK-DEPENDENT",
    "UKR - UKRAINE",
    "UNA - UN SPECIALIZED AGENCY",
    "UNH - UNHCR",
    "ARE - UNITED ARAB EMIRATES",
    "GBR - UNITED KINGDOM",
    "UNO - UNITED NATIONS ORGANIZATION",
    "UMI - UNITED STATES MINOR OUTLYING ISLANDS",
    "ZZZ - UNKNOWN",
    "ESH - UNKNOWN / UNSPECIFIED NATIONALITY",
    "XXX - UNSPECIFIED NATIONALITY",
    "URY - URUGUAY",
    "USA - USA",
    "UZB - UZBEKISTAN",
    "VUT - VANUATU",
    "VEN - VENEZUELA",
    "VNM - VIETNAM",
    "VGB - VIRGIN ISLANDS (BRITISH)",
    "VIR - VIRGIN ISLANDS (USA)",
    "WLF - WALLIS AND FUTURA ISLANDS",
    "YEM - YEMEN",
    "YUG - YUGOSLAVIA",
    "ZAR - ZAIRE",
    "ZMB - ZAMBIA",
    "ZWE - ZIMBABWE",
    "ZIM - ZIMBABWE"
  ],
  "accommodation": [
    "HOTEL/MOTEL/REST HOUSE",
    "RESIDENCE OF FRIENDS/RELATIVES",
    "OTHERS"
  ],
  "state": [
    "JOHOR",
    "KEDAH",
    "KELANTAN",
    "MELAKA",
    "NEGERI SEMBILAN",
    "PAHANG",
    "PULAU PINANG",
    "PERAK",
    "PERLIS",
    "SELANGOR",
    "TERENGGANU",
    "SABAH",
    "SARAWAK",
    "WP KUALA LUMPUR",
    "WP LABUAN",
    "WP PUTRAJAYA"
  ],
  "cities_by_state": {
    "JOHOR": [
      "JOHOR",
      "ASAHAN, JOHOR",
      "AYER BALOI",
      "AYER HITAM",
      "BAKRI",
      "BATU ANAM",
      "BATU PAHAT",
      "BEKOK",
      "BENUT",
      "BUKIT GAMBIR",
      "BUKIT PASIR",
      "CHAAH",
      "ENDAU",
      "GELANG PATAH",
      "GEMAS",
      "GERSEK",
      "G. TAIB ANDAK",
      "JEMENTAH",
      "JOHOR BAHRU",
      "KAHANG",
      "KLUANG",
      "KG KNGAN T DR",
      "KOTA TINGGI",
      "KUKUP",
      "KULAI",
      "LABIS",
      "LAYANG-LAYANG",
      "MASAI",
      "MERSING",
      "MUAR",
      "PAGOH",
      "PALOH",
      "PANCHOR",
      "PARIT JAWA",
      "PARIT RAJA",
      "PARIT SULONG",
      "PASIR GUDANG",
      "PEKAN NANAS",
      "PENGERANG",
      "PONTIAN",
      "RENGIT",
      "SEGAMAT",
      "SKUDAI",
      "SEMERAH",
      "SENAI",
      "SENGGARANG",
      "SIMPANG RENGGAM",
      "SUNGAI MATI",
      "TANGKAK",
      "ULU TIRAM",
      "YONG PENG",
      "SAGIL",
      "BUKIT KEPONG",
      "LENGA",
      "SUNGAI BALANG",
      "GEMAS BARU",
      "RENGGAM",
      "BANDAR PENAWAR",
      "LEDANG",
      "ISKANDAR PUTERI",
      "KULAI JAYA",
      "KANGKAR PULAI"
    ],
    "KEDAH": [
      "KEDAH",
      "ALOR SETAR",
      "BALING",
      "BANDAR BAHARU",
      "BEDONG",
      "GURUN",
      "JITRA",
      "KARANGAN",
      "KEPALA BATAS",
      "KODIANG",
      "KOTA KUALA MUDA",
      "KUALA KEDAH",
      "KUALA KETIL",
      "KUALA NERANG",
      "KULIM",
      "KUPANG",
      "LANGGAR",
      "LANGKAWI",
      "LUNAS",
      "MERBOK",
      "PADANG SERAI",
      "PENDANG",
      "POKOK SENA",
      "SERDANG",
      "SIK",
      "SUNGAI PETANI",
      "YAN",
      "CHANGLOON",
      "SINTOK",
      "SG. BAKAP",
      "BUKIT KAYU HITAM",
      "SIMPANG EMPAT",
      "KOTA SARANG SEMUT",
      "JENIANG",
      "SINTOK"
    ],
    "KELANTAN": [
      "KELANTAN",
      "AYER LANAS",
      "BACHOK",
      "CHERANG RUKU",
      "DABONG",
      "GUA MUSANG",
      "JELI",
      "K DESA PAHLAWAN",
      "KETEREH",
      "KOTA BHARU",
      "KUALA KRAI",
      "MACHANG",
      "MELOR",
      "PASIR MAS",
      "PASIR PUTEH",
      "PULAI CHONDONG",
      "RANTAU PANJANG",
      "TANAH MERAH",
      "TEMANGAN",
      "TUMPAT",
      "WAKAF BHARU",
      "SELISING",
      "KUALA BALAH"
    ],
    "MELAKA": [
      "MELAKA",
      "ALOR GAJAH",
      "ASAHAN",
      "BATANG MELAKA",
      "BEMBAN",
      "DURIAN TUNGGAL",
      "GEMAS",
      "JASIN",
      "K/SUNGAI BARU",
      "LUBOK CHINA",
      "MASJID TANAH",
      "MELAKA",
      "MERLIMAU",
      "SUNGAI RAMBAI",
      "SUNGAI UDANG",
      "TAMPIN",
      "TANJONG KELING",
      "SELANDAR",
      "BUKIT KATIL",
      "AYER KEROH",
      "BATU BERENDAM"
    ],
    "NEGERI SEMBILAN": [
      "N SEMBILAN",
      "ASAHAN",
      "BAHAU",
      "BATANG MELAKA",
      "BATU KIKIR",
      "DURIAN TIPUS",
      "GEMAS",
      "GEMENCHEH",
      "JOHOL",
      "KOTA",
      "KUALA KLAWANG",
      "KUALA PILAH",
      "LABU",
      "LENGGENG",
      "LINGGI",
      "LUBOK CHINA",
      "MANTIN",
      "NILAI",
      "PASIR PANJANG",
      "PEDAS",
      "PORT DICKSON",
      "RANTAU",
      "REMBAU",
      "ROMPIN",
      "SELIAU",
      "SEREMBAN",
      "SRI MENANTI",
      "SI RUSA",
      "SILIAU",
      "SIMPANG PERTANG",
      "SUNGAI GADUT",
      "TAMPIN",
      "TANJUNG IPOH",
      "TITI",
      "BUKIT PELANDOK",
      "CHUAH",
      "LUKUT",
      "TELUK KEMANG",
      "PENG.KEMPAS",
      "JELEBU",
      "BANDAR SERI JEMPOL",
      "JUASSEH",
      "B BARU JEMPOL",
      "BANDAR ENSTEK",
      "PUSAT BANDAR PALONG"
    ],
    "PAHANG": [
      "PAHANG",
      "BANDAR JENGKA",
      "BENTA",
      "BENTONG",
      "BESERAH",
      "BUKIT FRASER",
      "CHENOR",
      "DONG",
      "GAMBANG",
      "GENTING",
      "JERANTUT",
      "KARAK",
      "KEMAYAN",
      "KUALA LIPIS",
      "KUALA ROMPIN",
      "KUANTAN",
      "LANCHANG",
      "LURAH BILUT",
      "MARAN",
      "MENGKARAK",
      "MENTAKAB",
      "MERSING",
      "MUADZAM SHAH",
      "PADANG TENGKU",
      "PEKAN",
      "RAUB",
      "RINGLET",
      "SEGAMAT",
      "SUNGAI LEMBING",
      "SUNGAI RUAN",
      "TANAH RATA",
      "TEMERLOH",
      "TRIANG",
      "BDR TUN RAZAK",
      "ROMPIN",
      "C HIGHLANDS",
      "BANDAR BERA",
      "SEGA",
      "BRINCHANG"
    ],
    "PULAU PINANG": [
      "P PINANG",
      "AYER ITAM",
      "BALIK PULAU",
      "BATU FERRINGHI",
      "BAYAN LEPAS",
      "BUKIT MERTAJAM",
      "BUTTERWORTH",
      "GELUGOR",
      "GEORGETOWN",
      "KEPALA BATAS",
      "NIBONG TEBAL",
      "PENAGA",
      "PENANG HILL",
      "PERAI",
      "PERMATANG PAUH",
      "PULAU PINANG",
      "SIMPANG AMPAT",
      "SUNGAI JAWI",
      "TANJONG BUNGAH",
      "TASEK GELUGOR",
      "USM P/PINANG",
      "SUNGAI BAKAP",
      "JELUTONG",
      "MINDEN",
      "TANJONG TOKONG",
      "BAYAN BARU"
    ],
    "PERAK": [
      "PERAK",
      "AYER TAWAR",
      "BAGAN DATOH",
      "BAGAN SERAI",
      "BATU GAJAH",
      "BATU KURAU",
      "BERUAS",
      "BIDOR",
      "BOTA",
      "CHKT KERUING",
      "CHEMOR",
      "CHENDERIANG",
      "CHENDERONG BALAI",
      "ENGGOR",
      "GERIK",
      "GOPENG",
      "HUTAN MELINTANG",
      "KLIAN INTAN",
      "IPOH",
      "KAMPAR",
      "KAMPONG GAJAH",
      "KG KEPAYANG",
      "KAMUNTING",
      "KUALA KANGSAR",
      "KUALA SEPETANG",
      "LAHAT",
      "LANGKAP",
      "LENGGONG",
      "LUMUT",
      "MALIM NAWAR",
      "MAMBANG DIAWAN",
      "MANONG",
      "MATANG",
      "MENGLEMBU",
      "PADANG RENGAS",
      "PANGKOR",
      "PANTAI REMIS",
      "PARIT",
      "PARIT BUNTAR",
      "PENGKALAN HULU",
      "PUSING",
      "SAUK",
      "SELAMA",
      "SELEKOH",
      "SEMANGGOL",
      "SIMPANG",
      "SIMPANG AMPAT",
      "SITIAWAN",
      "SLIM RIVER",
      "SUNGAI SIPUT",
      "SUNGAI SUMUN",
      "SUNGKAI",
      "TAIPING",
      "TANJUNG MALIM",
      "TG.PIANDANG",
      "TG.RAMBUTAN",
      "TANJONG TUALANG",
      "TAPAH",
      "TAPAH ROAD",
      "TELUK INTAN",
      "TEMOH",
      "TRONG",
      "TERONOH",
      "ULU KINTA",
      "ULU BERNAM",
      "SG SIPUT (U)",
      "BEHRANG STESEN",
      "TROLAK",
      "KUALA DIPANG",
      "KUALA KURAU",
      "SERI MANJUNG",
      "RANTAU PANJANG",
      "CHIKUS"
    ],
    "PERLIS": [
      "PERLIS",
      "ARAU",
      "KAKI BUKIT",
      "KANGAR",
      "KUALA PERLIS",
      "PADANG BESAR",
      "SIMPANG AMPAT"
    ],
    "SELANGOR": [
      "SELANGOR",
      "AMPANG",
      "BANTING",
      "BTG.BERJUNTAI",
      "BATANG KALI",
      "BATU 9 CHERAS",
      "BATU ARANG",
      "BATU CAVES",
      "BERANANG",
      "BUKIT ROTAN",
      "DENGKIL",
      "HULU LANGAT",
      "JENJAROM",
      "JERAM",
      "KAJANG",
      "KAPAR",
      "KLANG",
      "KERLING",
      "K. KUBU BHARU",
      "KUALA LUMPUR",
      "KUALA SELANGOR",
      "NILAI",
      "MANTIN",
      "PELABUHAN KLANG",
      "PETALING JAYA",
      "PUCHONG",
      "PULAU CAREY",
      "PULAU KETAM",
      "PULAU INDAH",
      "RANTAU PANJANG",
      "RASA",
      "RAWANG",
      "SABAK BERNAM",
      "SEKINCAN",
      "SEMENYIH",
      "SEPANG",
      "SERENDAH",
      "SERI KEMBANGAN",
      "SHAH ALAM",
      "SUBANG JAYA",
      "SG AYER TAWAR",
      "SUNGAI BESAR",
      "SUNGAI BULOH",
      "SUNGAI PELEK",
      "TANJONG KARANG",
      "TANJONG SEPAT",
      "TELOK P. GARANG",
      "UKM BANGI",
      "UPM SERDANG",
      "HULU BERNAM",
      "BDR. BARU BANGI",
      "PUTRAJAYA(1.2.2001)",
      "CYBERJAYA",
      "SELAYANG",
      "BANDAR BARU SUNGAI BULOH",
      "ULU YAM BARU",
      "GOMBAK",
      "SERDANG",
      "TASIK PUTERI",
      "CHERAS",
      "BANDAR PUNCAK ALAM",
      "BANDAR PUNCAK ALAM"
    ],
    "TERENGGANU": [
      "TERENGGANU",
      "AJIL",
      "BESUT",
      "BUKIT BESI",
      "DUNGUN",
      "JERTIH",
      "BDR PERMAISURI",
      "KEMAMAN",
      "KEMASEK",
      "KIJAL",
      "KUALA BERANG",
      "KUALA BESUT",
      "KUALA TERENGGANU",
      "MARANG",
      "PAKA",
      "KERTEH",
      "MUKTAFI BILLAH SHAH",
      "KAMPONG RAJA",
      "CUKAI",
      "KUALA NERUS",
      "BANDAR KETENGAH JAYA"
    ],
    "SABAH": [
      "SABAH",
      "BEAUFORT",
      "BELURAN",
      "BONGAWAN",
      "INANAM",
      "KENINGAU",
      "KOTA BELUD",
      "KOTA KINABALU",
      "KOTA MARUDU",
      "KUALA PENYU",
      "KUDAT",
      "KUNAK",
      "LAHAD DATU",
      "LAMAG",
      "LIKAS",
      "MEMBAKUT",
      "MENUMBUK",
      "NABAWAN",
      "PAPAR",
      "PENAMPANG",
      "RANAU",
      "SANDAKAN",
      "SEMPORNA",
      "SIPITANG",
      "TAMBUNAN",
      "TAMPARULI",
      "TANJUNG ARU",
      "TAWAU",
      "TENOM",
      "TUARAN",
      "K. KINABATANGAN",
      "PUTATAN",
      "TELUPID"
    ],
    "SARAWAK": [
      "SARAWAK",
      "ASAJAYA",
      "BALINGIAN",
      "BARAM",
      "BAU",
      "BEKENU",
      "BELAGA",
      "BELAWAI",
      "BETONG",
      "BINTANGOR",
      "BINTULU",
      "DALAT",
      "DARO",
      "DEBAK",
      "ENGKILILI",
      "JULAU",
      "KABONG",
      "KANOWIT",
      "KAPIT",
      "KOTA SAMARAHAN",
      "KUCHING",
      "LAWAS",
      "LIMBANG",
      "LINGGA",
      "LONG LAMA",
      "LUBOK ANTU",
      "LUNDU",
      "MATU",
      "MIRI",
      "MUKAH",
      "NANGA MEDAMIT",
      "NIAH",
      "PEKENU",
      "PUSA",
      "ROBAN",
      "SARATOK",
      "SARIKEI",
      "SEBAUH",
      "SEBUYAU",
      "SERIAN",
      "SIMUNJAN",
      "SONG",
      "SPAOH",
      "SRI AMAN",
      "SUNDAR",
      "TATAU",
      "TEBAKANG",
      "SIBU",
      "BINTANGOR",
      "TEBEDU",
      "PAKAN",
      "SIBUTI",
      "OYA",
      "LAPANGAN TERBANG KOTA KINABALU",
      "MARUDI",
      "SIBURAN"
    ],
    "WP KUALA LUMPUR": [
      "W.PERSEKUTUAN",
      "KUALA LUMPUR",
      "CHERAS",
      "BATU CAVES"
    ],
    "WP LABUAN": [
      "W.P LABUAN"
    ],
    "WP PUTRAJAYA": [
      "PUTRAJAYA"
    ]
  }
};
